// Export utility functions for generating reports and invoices

interface ExportOptions {
  filename: string;
  format: 'csv' | 'json' | 'txt';
}

// Export data as CSV
export function exportAsCSV(data: Record<string, any>[], filename: string) {
  if (!data || data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map(row => 
      headers.map(header => {
        const value = row[header];
        // Handle arrays and objects
        if (typeof value === 'object') {
          return `"${JSON.stringify(value).replace(/"/g, '""')}"`;
        }
        // Handle strings with commas
        if (typeof value === 'string' && value.includes(',')) {
          return `"${value.replace(/"/g, '""')}"`;
        }
        return value ?? '';
      }).join(',')
    )
  ].join('\n');

  downloadFile(csvContent, `${filename}.csv`, 'text/csv');
}

// Export data as JSON
export function exportAsJSON(data: Record<string, any>, filename: string) {
  const jsonContent = JSON.stringify(data, null, 2);
  downloadFile(jsonContent, `${filename}.json`, 'application/json');
}

// Export text content
export function exportAsText(content: string, filename: string) {
  downloadFile(content, `${filename}.txt`, 'text/plain');
}

// Export creator report
export function exportCreatorReport(creator: {
  name: string;
  handle: string;
  platform: string;
  followers: string;
  engagement: string;
  trustScore: number;
  categories: string[];
  metrics?: any;
}) {
  const reportContent = `
╔══════════════════════════════════════════════════════════════════╗
║                    CREATOR ANALYSIS REPORT                       ║
║                         VibeVetting                              ║
╚══════════════════════════════════════════════════════════════════╝

Generated: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CREATOR PROFILE
───────────────────────────────────────────────────────────────────
Name:           ${creator.name}
Handle:         ${creator.handle}
Platform:       ${creator.platform}
Categories:     ${creator.categories?.join(', ') || 'N/A'}

PERFORMANCE METRICS
───────────────────────────────────────────────────────────────────
Followers:      ${creator.followers}
Engagement:     ${creator.engagement}
Trust Score:    ${creator.trustScore}/100

${creator.metrics ? `
DETAILED ANALYTICS
───────────────────────────────────────────────────────────────────
Avg. Likes:     ${creator.metrics.avgLikes || 'N/A'}
Avg. Comments:  ${creator.metrics.avgComments || 'N/A'}
Posts/Week:     ${creator.metrics.postsPerWeek || 'N/A'}
Growth Rate:    ${creator.metrics.growthRate || 'N/A'}
` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated by VibeVetting - AI-Powered Influencer Analytics
www.vibevetting.com
`.trim();

  downloadFile(reportContent, `${creator.handle.replace('@', '')}_report.txt`, 'text/plain');
}

// Export AI insights
export function exportAIInsights(title: string, content: string) {
  const reportContent = `
╔══════════════════════════════════════════════════════════════════╗
║                      AI INSIGHTS REPORT                          ║
║                         VibeVetting                              ║
╚══════════════════════════════════════════════════════════════════╝

Generated: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${title.toUpperCase()}
───────────────────────────────────────────────────────────────────

${content}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated by VibeVetting AI
`.trim();

  const filename = title.toLowerCase().replace(/\s+/g, '_');
  downloadFile(reportContent, `${filename}_${Date.now()}.txt`, 'text/plain');
}

// Export recommendations report
export function exportRecommendationsReport(recommendations: any[]) {
  let content = `
╔══════════════════════════════════════════════════════════════════╗
║                   AI RECOMMENDATIONS REPORT                      ║
║                         VibeVetting                              ║
╚══════════════════════════════════════════════════════════════════╝

Generated: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

  recommendations.forEach((category, idx) => {
    content += `
${(idx + 1)}. ${category.category?.toUpperCase() || 'RECOMMENDATION'}
───────────────────────────────────────────────────────────────────
`;
    if (category.recommendations) {
      category.recommendations.forEach((rec: any, recIdx: number) => {
        content += `
   ${recIdx + 1}. ${rec.title || 'Recommendation'}
      ${rec.description || ''}
      Impact: ${rec.impact || 'Medium'}
`;
      });
    }
  });

  content += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated by VibeVetting AI
`;

  downloadFile(content.trim(), `ai_recommendations_${Date.now()}.txt`, 'text/plain');
}

// Generate invoice content
export function generateInvoice(invoice: {
  invoiceNumber: string;
  date: string;
  planName: string;
  amount: number;
  paymentId: string;
  customerName: string;
  customerEmail: string;
}) {
  const invoiceContent = `
╔══════════════════════════════════════════════════════════════════╗
║                          TAX INVOICE                             ║
║                         VibeVetting                              ║
╚══════════════════════════════════════════════════════════════════╝

Invoice Number: ${invoice.invoiceNumber}
Date: ${invoice.date}

───────────────────────────────────────────────────────────────────
BILL TO
───────────────────────────────────────────────────────────────────
Name:  ${invoice.customerName}
Email: ${invoice.customerEmail}

───────────────────────────────────────────────────────────────────
PAYMENT DETAILS
───────────────────────────────────────────────────────────────────
Description                                              Amount (₹)
───────────────────────────────────────────────────────────────────
${invoice.planName} Plan - Monthly Subscription          ${invoice.amount.toLocaleString('en-IN')}


                                            ─────────────────────
                                            Subtotal: ₹${invoice.amount.toLocaleString('en-IN')}
                                            GST (18%): ₹${Math.round(invoice.amount * 0.18).toLocaleString('en-IN')}
                                            ─────────────────────
                                            Total: ₹${Math.round(invoice.amount * 1.18).toLocaleString('en-IN')}
                                            ─────────────────────

───────────────────────────────────────────────────────────────────
PAYMENT CONFIRMATION
───────────────────────────────────────────────────────────────────
Payment ID: ${invoice.paymentId}
Status: PAID
Payment Method: Razorpay

───────────────────────────────────────────────────────────────────

VibeVetting Technologies Pvt. Ltd.
GSTIN: 07AAACV1234F1ZS
Email: billing@vibevetting.com
Website: www.vibevetting.com

Thank you for your business!
`.trim();

  return invoiceContent;
}

// Download invoice
export function downloadInvoice(invoice: {
  invoiceNumber: string;
  date: string;
  planName: string;
  amount: number;
  paymentId: string;
  customerName: string;
  customerEmail: string;
}) {
  const content = generateInvoice(invoice);
  downloadFile(content, `Invoice_${invoice.invoiceNumber}.txt`, 'text/plain');
}

// Helper function to download file
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
